routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');
Route::get('/kontakt', 'HomeController@contact')->name('contact');
Route::get('/logowanie', 'HomeController@login')->name('logowanie');
Route::get('/profil/{id}', 'HomeController@profile')->name('profile');
Route::get('/edytuj/{id}', 'HomeController@edit')->name('edytuj');
Route::get('/addtofav/{id}', 'HomeController@fav')->name('fav');
Route::get('/delfav/{id}', 'HomeController@delfav')->name('delfav');
Route::get('/delcat/{id}', 'HomeController@delcat')->name('delcat');
Route::post('/edit_cats', 'HomeController@edit_cats')->name('edit_cats');
Route::post('/edit_desc', 'HomeController@edit_desc')->name('edit_desc');
Route::post('/edit_details', 'HomeController@edit_details')->name('edit_details');
Route::get('/wyloguj', 'HomeController@logout')->name('logout');
Route::get('/rejestracja', 'HomeController@register')->name('rejestracja');
Route::get('/fachowcy', 'HomeController@agents')->name('agents');
Route::get('/wyszukiwarka/{region}/{city}/{refval}/{category}', 'HomeController@search')->name('search');
Route::post('/search_form', 'HomeController@search_form')->name('search_form');
Route::post('/api/email_poster','HomeController@email_poster')->name('email_poster');
Route::post('/change_av', 'HomeController@change_av')->name('change_av');
Route::post('/crop_av', 'HomeController@crop_av')->name('crop_av');
Route::post('/gallery_add', 'HomeController@gallery_add')->name('gallery_add');
Route::get('/deletephoto/{id}', 'HomeController@deletephoto')->name('deletephoto');
Route::post('/addopinion', 'HomeController@addopinion')->name('addopinion');
Route::post('/registerpost', 'HomeController@registerpost')->name('registerpost');
Route::post('/contactsend', 'HomeController@contactsend')->name('contactsend');
Route::get('/getstate/{name}', 'HomeController@getstate')->name('getstate');
Route::get('/getcity/{name}', 'HomeController@getcity')->name('getcity');
Route::get('/getcat/{name}', 'HomeController@getcat')->name('getcat');

Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
Route::get('/updateusersavg', function () {
    \Illuminate\Support\Facades\Artisan::call('update:avg');
});
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Auth::routes();

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Categories;
use App\Fav;
use App\Opinion;
use App\User;
use App\userCategories;
use Carbon\Carbon;
use DeepCopy\f008\A;
use function GuzzleHttp\Psr7\str;
use Illuminate\Http\File;
use Illuminate\Http\Request;
use DB;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;
use Validator;
use Intervention\Image\Image;
use View;
use Mail;
use Illuminate\Support\Facades\Redirect;
use function MongoDB\BSON\toJSON;
use Psr\Http\Message\ServerRequestInterface;

class HomeController extends Controller
{
    public function __construct()
    {
        //its just a dummy data object.
        $counter = User::where('user_isperformer', 1)->count();
        $counter2 = User::where('user_isperformer', 0)->count();
        // Sharing is caring
        View::share('counter', $counter);
        View::share('counter2', $counter2);
    }

    public function email_poster(Request $request) {
      $file = fopen(public_path() . "/emails.txt", "w") or die("Unable to open file!");
      $txt = $request->get('emails');
      fwrite($file, "\n". $txt);
      fclose($file);

      return json_encode(['success' => $request->get('emails')]);
    }

    public function deletePhoto($id)
    {

        if (!Auth::user()->getMedia('portfolio')->where('id', $id)) return json_encode(['error' => 'Wybierz zdjęcie które chcesz usunąć.']);
        $photo = Auth::user()->getMedia('portfolio')->where('id', $id)->first()->delete();
        return json_encode(true);
    }

    public function gallery_add(Request $request)
    {
        if (!$request->hasFile('gallery_add')) return json_encode(['error' => 'Wybierz zdjęcie/zdjęcia.']);
        $urls = collect([]);
        foreach (collect($request->allFiles('gallery_add'))->get('gallery_add') as $file) {

            if (Auth::user()->getMedia('portfolio')->count() > 30) return json_encode(['error' => 'Możesz dodać maksymalnie 20 zdjęć do galerii.']);
            if (substr($file->getMimeType(), 0, 5) === 'image') {
                $img = \Intervention\Image\Facades\Image::make($file);
                if ($img->filesize() < 1500000) {
                    if ($img->width() > 1920) {
                        $img->resize(1920, null, function ($constraint) {
                            $constraint->aspectRatio();
                        });
                    }
                    $randomName = str_random() . '.' . $file->getClientOriginalExtension();
                    $path = public_path('/temp/' . $randomName);
                    $img->save($path);
                    $new = Auth::user()->addMedia($path)->toMediaCollection('portfolio');
                    if (file_exists($path)) unlink($path);
                }
            }
        }


        return json_encode(['success' => 'Zdjęcia zostaly dodane, będą widoczne po odświeżeniu.']);

    }

    public function change_av(Request $request)
    {

        if ($request->hasFile('avatar')) {
            $avatar = $request->file('avatar');
            $check = \Intervention\Image\Facades\Image::make($avatar);
            if ($check->filesize() > 1000000) return json_encode(['error' => 'Zdjęcie nie może przekraczać 1mb.']);
            $check->resize(320, null, function ($constraint) {
                $constraint->aspectRatio();
            });
            $check->save(public_path('/avatars/temp_' . Auth::user()->id . '.jpg'));

            return json_encode(['src' => 'temp_' . Auth::user()->id . '.jpg']);
        }
    }

    public function crop_av(Request $request)
    {

        $x = round($request->get('x'));
        $xx = round($request->get('xx'));
        $y = round($request->get('y'));
        $yy = round($request->get('yy'));
        if (file_exists(public_path('avatars/temp_' . Auth::user()->id . '.jpg'))) {

            $img = \Intervention\Image\Facades\Image::make(public_path('avatars/temp_' . Auth::user()->id . '.jpg'));
            $img->crop($xx, $yy, $x, $y);
            $img->save(public_path('avatars/' . Auth::user()->id . '.jpg'));

            $user = Auth::user();
            $user->clearMediaCollection('avatars');
            $user->addMedia(public_path('avatars/' . Auth::user()->id . '.jpg'))->toMediaCollection('avatars');


            return json_encode(['success' => 'Zapisano.', 'src' => Auth::user()->getFirstMediaUrl('avatars')]);
        }
        return json_encode(['error' => 'Błąd.']);
    }

    public function index()
    {
        $populars = User::whereHas('opinions')
            ->with('opinions')
            ->withCount('opinions')
            ->where('user_avg', '>=', 4)
            ->limit(8)
            ->get();

        return view('pages.home', compact('populars'));
    }

    public function contact()
    {
        return view('pages.contact');
    }

    public function search_form(Request $request)
    {
        $data = $request->all();
        $region = 'brak';
        $city = 'brak';
        $refval = 0;
        $category = 0;
        $data = collect($data);
        if ($data->get('state')) $region = $data->get('state');
        if ($data->get('city')) $city = $data->get('city');
        if ($data->get('refval')) $refval = $data->get('refval');
        if ($data->get('category')) $category = (Categories::where('name', $data->get('category'))->first())->id;

        return json_encode(['url' => route('search', [$region, $city, $refval, $category])]);
    }

    public function search($region, $city, $refval, $category)
    {

        $q = User::query();
        if ($region != 'brak') $q->where('user_state', $region);
        if ($city != 'brak') $q->where('user_city', $city);
        if ($category != 0) $q->whereHas('categories', function ($query) use ($category) {
            $query->join('categories', 'user_categories.category_id', '=', 'categories.id')->where('categories.id', $category);

        });
        if ($refval != 0) $q->where('user_avg', $refval);

        $users = $q->with('categories')->where('user_isperformer', 1)->withCount('opinions')->orderBy('user_avg', 'DESC')->paginate(20);
        return view('pages.search', compact('users', 'refval'));
    }

    public function agents()
    {

        if (Auth::check()) {
            $city = Auth::user()->user_city;
            $users = User::withCount('opinions')
                ->where('user_isperformer', 1)
                ->with('categories')
                ->orderByRaw("FIELD(user_city , '$city') DESC")
                ->orderBy('user_avg', 'DESC')
                ->paginate(20);
        } else {
            $users = User::withCount('opinions')->where('user_isperformer', 1)->with('categories')->orderBy('user_avg', 'DESC')->paginate(20);
        }
        return view('pages.agents', compact('users'));
    }

    public function edytuj($id)
    {

    }

    public function profile($id)
    {
        $user = User::where('id', $id)
            ->with('categories')
            ->with('opinions')
            ->with('followers')
            ->with('follows')
            ->first();

        return view('pages.profile', compact('user'));
    }

    public function edit($id)
    {
        if (Auth::user()->id != $id) return redirect(route('index'));
        $user = User::where('id', $id)
            ->with('categories')
            ->with('opinions')
            ->with('followers')
            ->with('follows')
            ->first();
        return view('pages.edit', compact('user'));
    }

    public function fav($id)
    {
        if (!$id) return Redirect::route('index');
        $fav_id = User::where('id', $id)->first();
        if (!$fav_id) return Redirect::route('index');
        if (!Auth::check()) return Redirect::route('profile', $id);
        $check = Fav::where('user_id', Auth::user()->id)->where('fav_id', $fav_id->id)->count();
        if ($check != 0) return Redirect::route('profile', $id);

        $newFav = new Fav();
        $newFav->user_id = Auth::user()->id;
        $newFav->fav_id = $fav_id->id;
        $newFav->created_at = Carbon::now();
        $newFav->save();

        if ($newFav) return Redirect::route('profile', $id);

    }

    public function edit_details(Request $request)
    {

        if (!Auth::check()) return json_encode(['error' => 'Coś poszło nie tak, upewnij się, że poprawnie wypełniłeś/łaś formularz.']);
        $data = collect($request->all());

        $user = $request->user();
        $user->user_city = $data->get('city');
        $user->user_zipcode = $data->get('zipcode');
        $user->user_country = $data->get('country');
        $user->user_fb = $data->get('fb');
        $user->user_tw = $data->get('tw');
        $user->user_regon = $data->get('regon');
        $user->user_nip = $data->get('nip');
        $user->company_name = $data->get('company_name');
        $user->user_url = $data->get('url');
        $user->user_state = $data->get('state');
        $user->user_number = $data->get('number');
        $user->user_address = $data->get('address');
        $user->save();

        return json_encode(['success' => 'Zapisano']);

    }

    public function edit_desc(Request $request)
    {

        if (!Auth::check()) return json_encode(['error' => 'Coś poszło nie tak, upewnij się, że poprawnie wypełniłeś/łaś formularz.']);
        $message = collect($request->all())->get('message');
        $userNow = $request->user();
        $userNow->user_desc = $message;
        $userNow->save();
        return json_encode(['success' => 'Zapisano']);

    }

    public function edit_cats(Request $request)
    {
        if (!Auth::check()) return json_encode(['error' => 'Coś poszło nie tak, upewnij się, że poprawnie wypełniłeś/łaś formularz.']);
        if (collect($request->all())->count() < 1) return json_encode(['error' => 'Musisz posiadać przynajmniej jedną przypisaną kategorię']);
        userCategories::where('user_id', $request->user()->id)->delete();

resources/views/partials/footer.blade.php
<footer class="footer footer-black footer-big">
    <div class="container">
        <div class="row">
            <div class="col-md-2 text-center col-sm-3 col-12 ml-auto mr-auto">
                <img style="    margin-top: 20px;
    width: 120px;" src="{{asset('images/logo.png')}}" alt="">
            </div>
            <div class="col-md-9 col-sm-9 col-12 ml-auto mr-auto">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-6">
                        <div class="links">
                            <ul class="uppercase-links stacked-links">
                                <li>
                                    <a href="{{route('index')}}">
                                        Strona Główna
                                    </a>
                                </li>
                                <li>
                                    <a href="{{route('agents')}}">
                                        Fachowcy
                                    </a>
                                </li>
                                <li>
                                    <a href="{{route('contact')}}">
                                        Kontakt
                                    </a>
                                </li>

                            </ul>

                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 col-6">
                        <div class="links">
                            <ul class="uppercase-links stacked-links">
                                <li>
                                    <a href="{{route('rejestracja')}}">
                                        Zarejestruj się
                                    </a>
                                </li>
                                <li>
                                    <a href="{{route('logowanie')}}">
                                        Zaloguj się
                                    </a>
                                </li>
                                @if(!Auth::check())
                                    <li>
                                        <a href="{{route('logowanie')}}">Twój profil</a>
                                    </li>
                                @else
                                    <li>
                                        <a href="profil/{{Auth::user()->id}}">Twój profil</a>
                                    </li>
                                @endif
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 col-6">
                        <div class="links">
                            <ul class="uppercase-links stacked-links">
                                <li>
                                    <a target="_blank" href="{{asset('pomoc.pdf')}}">pomoc</a>
                                </li>
                                <li>
                                    <a target="_blank" href="{{asset('pliki cookie.pdf')}}">Pliki Cookie</a>
                                </li>
                                <li>
                                    <a target="_blank" href="{{asset('polityka-prywatnosci.pdf')}}">Polityka Prywatności</a>
                                </li>

                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 col-6">
                        <div class="links">
                            <ul class="stacked-links">
                                <li>
                                    <h4>{{$counter}}<br> <small>wykonawców</small></h4>
                                </li>
                                <li>
                                    <h4>{{$counter2}}<br> <small>klientów</small></h4>
                                </li>

                            </ul>
                        </div>
                    </div>
                </div>
                <hr>
                <div class="copyright">
                    <div class="pull-left text-left text-danger">
                        © <script>document.write(new Date().getFullYear())</script> Twoja-Ekipa <i class="fa fa-heart heart"></i> Wszelkie Prawa Zastrzeżone
                        <br><a style="color: #ffffff !important;font-weight: 500;font-size: 14px;" href="https://gowebsite.pl" target="_blank" class="text-danger">projekt / wykonanie strony : Gowebsite.pl</a>
                    </div>
                    <div class="links pull-right">
                        <ul>
                            <li>
                                <a target="_blank" href="{{asset('pomoc.pdf')}}">Pomoc</a>
                            </li>
                            -
                            <li>
                                <a target="_blank" href="{{asset('pliki cookie.pdf')}}">Pliki Cookie</a>
                            </li>
                            -
                            <li>
                                <a target="_blank" href="{{asset('polityka-prywatnosci.pdf')}}">Polityka Prywatności</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
</footer>

resources/views/partials/populars.blade.php
<div class="col-md-3">
    <div class="card card-profile card-plain">
        <div class="card-avatar">
            <a href="{{route('profile', $popular->id)}}"> @include('partials.components.avatar', ['avatar' => $popular->getFirstMediaUrl('avatars')])</a>

        </div>
        <div class="card-body">
            <a href="{{route('profile', $popular->id)}}">
                <div class="author">
                    <h4 class="card-title">{{$popular->user_nicename}}</h4>
                    <h6 class="card-category text-muted">@if($popular->user_isperformer)
                            Wykonawca @else Klient @endif</h6>
                    <small class="">
                        <?php $c = 1; ?>
                        @foreach($popular->categories as $cat)
                            @if($c <= 5)
                                {{$cat->name}} @if($cat != $popular->categories->last())
                                    , @endif
                            @endif
                            <?php $c++; ?>
                        @endforeach
                    </small>
                </div>
            </a>
            @if($popular->user_desc)
                <p class="card-description text-center">
                    {{\Illuminate\Support\Str::limit($popular->user_desc, 55)}}
                </p>
            @endif
            <h6 class="card-category text-muted">Średnia ocena
                : @if($popular->user_avg == 0) Brak
                ocen @else {{$popular->user_avg}}
                <i class="fa fa-star"></i>@endif </h6>
            <h6 class="card-category text-muted">Opinii : @if($popular->opinions_count == 0)
                    Brak opinii @else {{$popular->opinions_count}} <i
                            class="fa fa-comment"></i>@endif</h6>
        </div>
    </div>
</div>

resources/views/partials/scripts.blade.php
<script src="{{asset('js/jquery-3.2.1.min.JS')}}" type="text/javascript"></script>
<script src="{{asset('js/jquery-ui-1.12.1.custom.min.js')}}" type="text/javascript"></script>
<script src="{{asset('js/popper.js')}}" type="text/javascript"></script>
<script src="{{asset('js/bootstrap.min.js')}}" type="text/javascript"></script>

<!-- Switches -->
<script src="{{asset('js/bootstrap-switch.min.js')}}"></script>

<!--  Plugins for Slider -->
<script src="{{asset('js/nouislider.js')}}"></script>

<!--  Plugins for DateTimePicker -->
<script src="{{asset('js/moment.min.js')}}"></script>
<script src="{{asset('js/bootstrap-datetimepicker.min.js')}}"></script>

<!--  Paper Kit Initialization and functons -->
<script src="{{asset('js/paper-kit.js?v=2.1.0')}}"></script>
<script src="//unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script src="{{asset('js/main.js')}}"></script>
<script src="{{asset('js/buttons.js')}}"></script>
<script src="{{asset('js/bootstrap-select.js')}}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.11.1/sweetalert2.min.js"></script>
<script src='//www.google.com/recaptcha/api.js'></script>
<script src="{{asset('js/demo.js ')}}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/cropper/3.1.3/cropper.min.js"></script>
<script type="text/javascript">
    (function () {
        function getRandomInt(min, max) {
            return Math.floor(Math.random() * (max - min + 1)) + min;
        }
    })();
</script>
<script>
    $(function () {
        $(window).scrollTop($(window).scrollTop() - 1);
        $(window).scrollTop($(window).scrollTop() + 1);
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    });

</script>

<script src="{{asset('js/optimalization.js')}}"></script>
<script src="{{asset('js/pl.js')}}"></script>
<script>
    $(function () {
        $('.deletephoto').on('click', function () {
            var id = $(this).attr('media_id');
            $.get('/deletephoto/' + id, function (data) {
                if (data == 'true') {
                    $('span[media_id=' + id + ']').parent().remove();
                    $('#gallery').masonry('destroy');
                    $('#gallery').masonry({
                        // options
                        itemSelector: '.grid-item',
                    })
                }
            });
        });

        $('.search_form').on('submit', function () {
            $('.search_form button[type=submit]').html('Proszę czekać');
            $.ajax({
                type: 'post',
                url: '{{route('search_form')}}',
                dataType: 'json',
                data: $(this).serialize(),
                success: function (data) {
                    if (data['error']) {
                        swal(
                            '',
                            '' + data['error'] + '',
                            'error'
                        )
                    } else {
                        window.location.replace(data['url']);
                    }
                },
                error: function (data) {
                    swal(
                        '',
                        'Sprawdź czy pola są wypełnione poprawnie.',
                        'error'
                    )
                }
            });

            return false;
        });

        $('.cards-gal').masonry({
            // options
            itemSelector: '.grid-item',
        });
        $('#gallery').masonry({
            // options
            itemSelector: '.grid-item'
        });



        var submitGalleryAdd = function (e) {
            var formData = new FormData(this);
            $('.gallery_loader').toggleClass('active');
            $.ajax({
                type: 'POST',
                url: "{{route('gallery_add')}}",
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    $('.gallery_loader').toggleClass('active');
                    data = JSON.parse(data);
                    if (data['success']) {
                        swal(
                            '',
                            '' + data['success'] + '',
                            'success'
                        )
                    }
                    if (data['error']) {
                        swal(
                            '',
                            '' + data['error'] + '',
                            'error'
                        )
                    } else {

                    }
                }
            });
            return false;
        };
        $('#gallery_add input').on('change', function () {
            $('#gallery_add').submit()
        });
        $('#gallery_add').on('submit', submitGalleryAdd);
        $('#service_date').datetimepicker({
            locale: 'pl',
            format: 'MMMM'
        });
        $('.stars_check .card-stars i').on('mouseenter', function () {
            $(this).parent().find('i').removeClass('active');
            var index = $(this).index();
            var this_index = 1;
            for (this_index = 1; this_index < index + 2; this_index++) {
                $(this).parent().find('i:nth-child(' + this_index + ')').addClass('active');
            }
            ;
        });
        $('.stars_check .card-stars i').on('click', function () {
            var rate = $(this).index() + 1;
            $(this).parent().parent().find('input').val(rate);
        });

        var addopinion = function (e) {
            var formData = new FormData(this);
            $.ajax({
                type: 'POST',
                url: "{{route('addopinion')}}",
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    data = JSON.parse(data);
                    if (data.errors) {
                        $('#add_opinion').find('label').find('small.has-error').remove();
                        $('#add_opinion').find('input.form-control').removeClass('has-error');
                        $.each(data.errors, function (key, value) {
                            $('#add_opinion *[name=' + key + ']').addClass('has-error');
                            $('#add_opinion *[name=' + key + ']').parent().find('label:first-of-type').append('<small class="has-error"><small class="control-label"> ' + value + '</small></small>');
                        });

                        $('html, body').animate({
                            scrollTop: $('.has-error').offset().top - 300
                        }, 100);
                    }
                    if (data.error) {
                        swal(
                            '',
                            '' + data.error + '',
                            'error'
                        )
                    }
                    if (data.success) {
                        swal(
                            '',
                            '' + data.success + '',
                            'success'
                        )
                    }
                }
            });
            return false;
        };

        $('#add_opinion textarea[name=message]').on('keyup', function () {
            $(this).parent().find('label:last-of-type small').html('Pozostało: ' + (1000 - $(this).val().length) + '/1000 znaków.');
            if ((1000 - $(this).val().length) < 1) $(this).parent().find('label:last-of-type').removeClass('text-info').addClass('text-danger');
            if ($(this).val().length < 50) $('#add_opinion button[type=submit]').attr('disabled', 'disabled');
            if ((1000 - $(this).val().length) > 1) $(this).parent().find('label:last-of-type').removeClass('text-danger').addClass('text-info');
            if ($(this).val().length > 50) $('#add_opinion button[type=submit]').removeAttr('disabled');
        });
        $('#add_opinion').on('submit', addopinion);
    });
    $(document).ready(function () {

        setTimeout(function () {
            if ($('#gallery').length) {
                $('#gallery').masonry({
                    // options
                    itemSelector: '.grid-item'
                });
            }
        }, 500);
    });
</script>
<script src="{{asset('js/lightbox.min.js')}}"></script>

resources/views/partials/style.blade.php
<link href='//fonts.googleapis.com/css?family=Montserrat:400,300,700' rel='stylesheet' type='text/css'>
<link href="//maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
<link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet" />
<link href="{{asset('css/paper-kit.css')}}" rel="stylesheet"/>
<link href="{{asset('css/demo.css')}}" rel="stylesheet" />
<link href="{{asset('css/nucleo-icons.css')}}" rel="stylesheet">
<link href="{{asset('css/lightbox.min.css')}}" rel="stylesheet">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/cropper/3.1.3/cropper.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.11.1/sweetalert2.min.css">
<style type="text/css">
    :root [class^="ad-"]
    { display: none !important; }</style>